---
title: "Programming"
author: "Elias Joneborg"
date: "2/8/2022"
output: html_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyr)

library(tidyr)

swetrau_scrambled <- read.csv("swetrau-scrambled.csv")
problem_scrambled <- read.csv("problem-scrambled.csv")


problem_scrambled$probYN <- with(problem_scrambled, ifelse(Problemomrade_.FMP == "ok" | Problemomrade_.FMP == "OK" | Problemomrade_.FMP == "Ok" | Problemomrade_.FMP == "Föredömligt handlagd", "NO", "YES"))

problemområde<-na.omit(problem_scrambled)

problemområde2<- merge(swetrau_scrambled, problemområde, by= "id")

library(dplyr)

problemområde3<-problemområde2 %>% select(inj_dominant, pt_age_yrs, Problemomrade_.FMP, NISS, ed_gcs_sum, pre_intub_type, pre_sbp_value, pre_sbp_rtscat, ed_sbp_value, ed_sbp_rtscat, 151:201, Ankomst_te)


#AISFIX

library(stringr)

AIS <-problemområde4 %>% select(12:61)

getLastNumber = function(x) str_sub(x, 8L, 8L)

AIS2 <- apply(AIS, c(1,2), getLastNumber)

AIS2=as.data.frame(AIS2)

#creating new datafram "AIS2" with variables representing AIS severity(1-50) 

names(AIS2) <- c('AIS_sev01', 'AIS_sev02', 'AIS_sev03', 'AIS_sev04', 'AIS_sev05', 'AIS_sev06', 'AIS_sev07', 'AIS_sev08', 'AIS_sev09', 'AIS_sev10',
                 'AIS_sev11', 'AIS_sev12', 'AIS_sev13', 'AIS_sev14', 'AIS_sev15', 'AIS_sev16', 'AIS_sev17', 'AIS_sev18', 'AIS_sev19',
                 'AIS_sev20', 'AIS_sev21', 'AIS_sev22', 'AIS_sev23', 'AIS_sev24', 'AIS_sev25', 'AIS_sev26', 'AIS_sev27', 'AIS_sev28',
                 'AIS_sev29', 'AIS_sev30', 'AIS_sev31', 'AIS_sev32', 'AIS_sev33', 'AIS_sev34', 'AIS_sev35', 'AIS_sev36', 'AIS_sev37',
                 'AIS_sev38', 'AIS_sev39', 'AIS_sev40', 'AIS_sev41', 'AIS_sev42', 'AIS_sev43', 'AIS_sev44', 'AIS_sev45', 'AIS_sev46',
                 'AIS_sev47', 'AIS_sev48', 'AIS_sev49', 'AIS_sev50')

problemområde5<-cbind(problemområde4, AIS2)

#add new variables as columns into dataframe

#BLUNT MULTISYSTEM

is_serious <- function(code) {
  severity <- substr(as.character(code), 8, 8)
  as.numeric(severity) >= 3  # if severity level is 3 or higher, the injury is considered serious
}

####
# Identify distinct regions
####

# Expects a vector of codes
number_of_regions <- function(code) {
  region <- substr(as.character(code), 1, 1)
  length(unique(region))
}

###
# Putting them together
###

has_more_than_one_serious_injury <- function(code) {
  code <- code[!is.na(code)]
  serious_injury <- is_serious(code)
  number_of_regions(code[serious_injury]) >= 2
}

###
# Apply on dataset
###

# Creates column blunt_multisystem with TRUE/FALSE 

swetrau_scrambled$blunt_multisystem <- NA
swetrau2 <- swetrau_scrambled[!is.na(swetrau_scrambled$inj_dominant), ] #Need to remove not known in inj_dominant

for (i in 1:nrow(swetrau2)) {
  v = 0+i
  if (has_more_than_one_serious_injury(swetrau2[v,grepl( "AISCode" , names(swetrau_scrambled))]) == TRUE && swetrau2[v,"inj_dominant"] == 1) {
    swetrau2[v,"blunt_multisystem"] <- TRUE
  } else {
    swetrau2[v,"blunt_multisystem"] <- FALSE
  }
}

# SHOCK

swetrau2$ed_sbp_value[is.na(swetrau2$ed_sbp_value)]<-350

swetrau2$ed_sbp_value[swetrau2$ed_sbp_value>=0 & swetrau2$ed_sbp_value<=49]<-1
swetrau2$ed_sbp_value[swetrau2$ed_sbp_value>=50 & swetrau2$ed_sbp_value<=75]<-2
swetrau2$ed_sbp_value[swetrau2$ed_sbp_value>=76 & swetrau2$ed_sbp_value<=89]<-3
swetrau2$ed_sbp_value[swetrau2$ed_sbp_value>89 & swetrau2$ed_sbp_value<=298]<-4
swetrau2$ed_sbp_value[swetrau2$ed_sbp_value==350]<-5
swetrau2$ed_sbp_value[swetrau2$ed_sbp_value==999]<-5

swetrau2$sbp_rts<-with(swetrau2, ifelse(ed_sbp_rtscat!=999 & is.na(swetrau2$ed_sbp_rtscat)==FALSE,ed_sbp_rtscat,ed_sbp_value))

swetrau2$shock <- NA
swetrau2$shock <- with(swetrau2, ifelse(sbp_rts <= 3 & sbp_rts != 0, TRUE, FALSE))

#GERIATRIC

swetrau2$geriatric <- NA
swetrau2$geriatric <- with(swetrau2, ifelse(pt_age_yrs>65 & pt_age_yrs<120, TRUE, FALSE))

#PENETRATING

neck_chest_abdomen_region <- function(code) {
  region <- substr(as.character(code), 1, 1)
  as.numeric(region) >= 3 &&  as.numeric(region)<=5
}
    
serious_neck_chest_abdomen_injury <- function(code) {
  code <- code[!is.na(code)]
  serious_injury <- is_serious(code)
  neck_chest_abdomen_region(code[serious_injury]) 
}

swetrau2$penetrating <- NA
for (i in 1:nrow(swetrau2)) {
  v = 0+i
  if (isTRUE(serious_neck_chest_abdomen_injury(swetrau2[v,grepl( "AISCode" , names(swetrau2))])) && swetrau2[v, "inj_dominant"] == 2) {
    swetrau2[v,"penetrating"] <- TRUE
  } else {
    swetrau2[v,"penetrating"] <- FALSE
  }
}

#SEVERE TBI

head_region <- function(code) {
  region <- substr(as.character(code), 1, 1)
  as.numeric(region) == 1
}

has_a_serious_head_injury <- function(code) {
  serious_injury <- is_serious(code)
  head_region(code[serious_injury]) 
}

#creating column GCS below nine

swetrau2$gcs_below_9 <- NA
swetrau2$gcs_below_9 <- with(swetrau2, ifelse(ed_gcs_sum<=8 | pre_intub_type==1, TRUE, FALSE))
swetrau2$gcs_below_9 <- with(swetrau2, ifelse(is.na(gcs_below_9) | isFALSE(gcs_below_9), FALSE, TRUE))

only_one_serious_injury_region <- function(code) {
  code <- code[!is.na(code)]
  serious_injury <- is_serious(code)
  number_of_regions(code[serious_injury]) = 1
}

#Make column severe_tbi where output is either TRUE or FALSE

swetrau2$severe_tbi <- NA

for (i in 1:nrow(swetrau2)) {
  v = 0+i
if (has_a_serious_head_injury(swetrau2[v, grepl("AISCode", names(swetrau_scrambled))]) && number_of_regions(swetrau2[v, grepl("AISCode", names(swetrau_scrambled))]) == TRUE && only_one_serious_injury_region(swetrau2[v, grepl ("AISCode", names(swetrau_scrambled))]) == TRUE && swetrau2[v, "gcs_below_9"] == TRUE) {
    swetrau2[v,"severe_tbi"] <- TRUE
  } else {
    swetrau2[v,"severe_tbi"] <- FALSE
  }
}


# GAMMAL KOD

# SHOCK
library(dplyr)

problemområde5$ed_sbp_value[is.na(problemområde5$ed_sbp_value)]<-350
problemområde5$ed_sbp_value[problemområde5$ed_sbp_value>=1 & problemområde5$ed_sbp_value<=49]<-1
problemområde5$ed_sbp_value[problemområde5$ed_sbp_value>=50 & problemområde5$ed_sbp_value<=75]<-2
problemområde5$ed_sbp_value[problemområde5$ed_sbp_value>=76 & problemområde5$ed_sbp_value<=89]<-3
problemområde5$ed_sbp_value[problemområde5$ed_sbp_value>89 & problemområde5$ed_sbp_value<=298]<-4
problemområde5$ed_sbp_value[problemområde5$ed_sbp_value==350]<-5
problemområde5$ed_sbp_value[problemområde5$ed_sbp_value==999]<-5

# Tar RTS värdet från ed, om det inte finns så använder den vanliga blodtrycket, som är grupperat enligt RTS.

problemområde5$sbp_rts<-with(problemområde5, ifelse(ed_sbp_rtscat!=999 & 
                                                      is.na(problemområde5$ed_sbp_rtscat)==FALSE,ed_sbp_rtscat,ed_sbp_value))

Shock_cohort <- filter(problemområde5, sbp_rts==1 |sbp_rts==2|sbp_rts==3)

library(table1)

Shock_cohort$inj_dominant<-factor(Shock_cohort$inj_dominant, levels=c(1,2),
       labels=c("Blunt", "Penetrating"))
label(Shock_cohort$NISS)              <- "New Injury Severity Score"
label(Shock_cohort$pre_sbp_value)    <- "Pre Hospital Systolic BP"
label(Shock_cohort$ed_sbp_value)     <- "Emergency Department Systolic BP"
units(Shock_cohort$pre_sbp_value)  <- "mmHg"
units(Shock_cohort$ed_sbp_value)   <- "mmHg"
table1(~ inj_dominant + NISS + pre_sbp_value + ed_sbp_value | inj_dominant, data=Shock_cohort)

# SEVERE TBI

    TBI_1 <-filter(problemområde5, AISCode_01 <200000 & AISCode_01 >100000 & AIS_sev01>2 & AIS_sev01<7)
    TBI_2 <-filter(problemområde5, AISCode_02 <200000 & AISCode_02 >100000 & AIS_sev02>2 & AIS_sev02<7)
    TBI_3 <-filter(problemområde5, AISCode_03 <200000 & AISCode_03 >100000 & AIS_sev03>2 & AIS_sev03<7)
    TBI_4 <-filter(problemområde5, AISCode_04 <200000 & AISCode_04 >100000 & AIS_sev04>2 & AIS_sev04<7)
    TBI_5 <-filter(problemområde5, AISCode_05 <200000 & AISCode_05 >100000 & AIS_sev05>2 & AIS_sev05<7)
    TBI_6 <-filter(problemområde5, AISCode_06 <200000 & AISCode_06 >100000 & AIS_sev06>2 & AIS_sev06<7)
    TBI_7 <-filter(problemområde5, AISCode_07 <200000 & AISCode_07 >100000 & AIS_sev07>2 & AIS_sev07<7)
    TBI_8 <-filter(problemområde5, AISCode_08 <200000 & AISCode_08 >100000 & AIS_sev08>2 & AIS_sev08<7)
    TBI_9 <-filter(problemområde5, AISCode_09 <200000 & AISCode_09 >100000 & AIS_sev09>2 & AIS_sev09<7)
    TBI_10 <-filter(problemområde5, AISCode_10 <200000 & AISCode_10 >100000 & AIS_sev10>2 & AIS_sev10<7)
    TBI_11 <-filter(problemområde5, AISCode_11 <200000 & AISCode_11 >100000 & AIS_sev11>2 & AIS_sev11<7)
    TBI_12 <-filter(problemområde5, AISCode_12 <200000 & AISCode_12 >100000 & AIS_sev12>2 & AIS_sev12<7)
    TBI_13 <-filter(problemområde5, AISCode_13 <200000 & AISCode_13 >100000 & AIS_sev13>2 & AIS_sev13<7)
    TBI_14 <-filter(problemområde5, AISCode_14 <200000 & AISCode_14 >100000 & AIS_sev14>2 & AIS_sev14<7)
    TBI_15 <-filter(problemområde5, AISCode_15 <200000 & AISCode_15 >100000 & AIS_sev15>2 & AIS_sev15<7)
    TBI_16 <-filter(problemområde5, AISCode_16 <200000 & AISCode_16 >100000 & AIS_sev16>2 & AIS_sev16<7)
    TBI_17 <-filter(problemområde5, AISCode_17 <200000 & AISCode_17 >100000 & AIS_sev17>2 & AIS_sev17<7)
    TBI_18 <-filter(problemområde5, AISCode_18 <200000 & AISCode_18 >100000 & AIS_sev18>2 & AIS_sev18<7)
    TBI_19 <-filter(problemområde5, AISCode_19 <200000 & AISCode_19 >100000 & AIS_sev19>2 & AIS_sev19<7)
    TBI_20 <-filter(problemområde5, AISCode_20 <200000 & AISCode_20 >100000 & AIS_sev20>2 & AIS_sev20<7)
    TBI_21 <-filter(problemområde5, AISCode_21 <200000 & AISCode_21 >100000 & AIS_sev21>2 & AIS_sev21<7)
    TBI_22 <-filter(problemområde5, AISCode_22 <200000 & AISCode_22 >100000 & AIS_sev22>2 & AIS_sev22<7)
    TBI_23 <-filter(problemområde5, AISCode_23 <200000 & AISCode_23 >100000 & AIS_sev23>2 & AIS_sev23<7)
    TBI_24 <-filter(problemområde5, AISCode_24 <200000 & AISCode_24 >100000 & AIS_sev24>2 & AIS_sev24<7)
    TBI_25 <-filter(problemområde5, AISCode_25 <200000 & AISCode_25 >100000 & AIS_sev25>2 & AIS_sev25<7)
    TBI_26 <-filter(problemområde5, AISCode_26 <200000 & AISCode_26 >100000 & AIS_sev26>2 & AIS_sev26<7)
    TBI_27 <-filter(problemområde5, AISCode_27 <200000 & AISCode_27 >100000 & AIS_sev27>2 & AIS_sev27<7)
    TBI_28 <-filter(problemområde5, AISCode_28 <200000 & AISCode_28 >100000 & AIS_sev28>2 & AIS_sev28<7)
    TBI_29 <-filter(problemområde5, AISCode_29 <200000 & AISCode_29 >100000 & AIS_sev29>2 & AIS_sev29<7)
    TBI_30 <-filter(problemområde5, AISCode_30 <200000 & AISCode_30 >100000 & AIS_sev30>2 & AIS_sev30<7)
    TBI_31 <-filter(problemområde5, AISCode_31 <200000 & AISCode_31 >100000 & AIS_sev31>2 & AIS_sev31<7)
    TBI_32 <-filter(problemområde5, AISCode_32 <200000 & AISCode_32 >100000 & AIS_sev32>2 & AIS_sev32<7)
    TBI_33 <-filter(problemområde5, AISCode_33 <200000 & AISCode_33 >100000 & AIS_sev33>2 & AIS_sev33<7)
    TBI_34 <-filter(problemområde5, AISCode_34 <200000 & AISCode_34 >100000 & AIS_sev34>2 & AIS_sev34<7)
    TBI_35 <-filter(problemområde5, AISCode_35 <200000 & AISCode_35 >100000 & AIS_sev35>2 & AIS_sev35<7)
    TBI_36 <-filter(problemområde5, AISCode_36 <200000 & AISCode_36 >100000 & AIS_sev36>2 & AIS_sev36<7)
    TBI_37 <-filter(problemområde5, AISCode_37 <200000 & AISCode_37 >100000 & AIS_sev37>2 & AIS_sev37<7)
    TBI_38 <-filter(problemområde5, AISCode_38 <200000 & AISCode_38 >100000 & AIS_sev38>2 & AIS_sev38<7)
    TBI_39 <-filter(problemområde5, AISCode_39 <200000 & AISCode_39 >100000 & AIS_sev39>2 & AIS_sev39<7)
    TBI_40 <-filter(problemområde5, AISCode_40 <200000 & AISCode_40 >100000 & AIS_sev40>2 & AIS_sev40<7)
    TBI_41 <-filter(problemområde5, AISCode_41 <200000 & AISCode_41 >100000 & AIS_sev41>2 & AIS_sev41<7)
    TBI_42 <-filter(problemområde5, AISCode_42 <200000 & AISCode_42 >100000 & AIS_sev42>2 & AIS_sev42<7)
    TBI_43 <-filter(problemområde5, AISCode_43 <200000 & AISCode_43 >100000 & AIS_sev43>2 & AIS_sev43<7)
    TBI_44 <-filter(problemområde5, AISCode_44 <200000 & AISCode_44 >100000 & AIS_sev44>2 & AIS_sev44<7)
    TBI_45 <-filter(problemområde5, AISCode_45 <200000 & AISCode_45 >100000 & AIS_sev45>2 & AIS_sev45<7)
    TBI_46 <-filter(problemområde5, AISCode_46 <200000 & AISCode_46 >100000 & AIS_sev46>2 & AIS_sev46<7)
    TBI_47 <-filter(problemområde5, AISCode_47 <200000 & AISCode_47 >100000 & AIS_sev47>2 & AIS_sev47<7)
    TBI_48 <-filter(problemområde5, AISCode_48 <200000 & AISCode_48 >100000 & AIS_sev48>2 & AIS_sev48<7)
    TBI_49 <-filter(problemområde5, AISCode_49 <200000 & AISCode_49 >100000 & AIS_sev49>2 & AIS_sev49<7)
    TBI_50 <-filter(problemområde5, AISCode_50 <200000 & AISCode_50 >100000 & AIS_sev50>2 & AIS_sev50<7)

   SevereTBI_cohort <- Reduce(function(x, y) merge(x, y, all=TRUE),
                              list(TBI_1, TBI_2, TBI_3, TBI_4, TBI_5,
                                   TBI_6, TBI_7, TBI_8, TBI_9, TBI_10,
                                   TBI_11, TBI_12, TBI_13, TBI_14, TBI_15,
                                   TBI_16, TBI_17, TBI_18, TBI_19, TBI_20,
                                   TBI_21, TBI_22, TBI_23, TBI_24, TBI_25,
                                   TBI_26, TBI_27, TBI_28, TBI_29, TBI_30,
                                   TBI_31, TBI_32, TBI_33, TBI_34, TBI_35,
                                   TBI_36, TBI_37, TBI_38, TBI_39, TBI_40,
                                   TBI_41, TBI_42, TBI_43, TBI_44, TBI_45,
                                   TBI_46, TBI_47, TBI_48, TBI_49, TBI_50))
  library(table1)
   
SevereTBI_cohort1 <-filter(SevereTBI_cohort, ed_gcs_sum<9 | pre_intub_type==1)

   
SevereTBI_cohort1$inj_dominant<-factor(SevereTBI_cohort1$inj_dominant, levels=c(1,2), labels=c("Blunt", "Penetrating"))

                   label(SevereTBI_cohort1$NISS)              <- "New Injury Severity Score"
                    label(SevereTBI_cohort1$inj_dominant)              <- "Dominant Injury"
                   label(SevereTBI_cohort1$pt_age_yrs)              <- "Age"
                   label(SevereTBI_cohort1$pre_sbp_value)    <- "Pre Hospital Systolic BP"
                   label(SevereTBI_cohort1$ed_sbp_value)     <- "Emergency Department Systolic BP"

                  units(SevereTBI_cohort1$pre_sbp_value)  <- "mmHg"
                  units(SevereTBI_cohort1$ed_sbp_value)   <- "mmHg"
                  units(SevereTBI_cohort1$pt_age_yrs)   <- "years"

                   table1(~ pt_age_yrs + NISS + pre_sbp_value + ed_sbp_value, data=SevereTBI_cohort1, overall="Severe Traumatic Brain Injury")
                   
library(dplyr)

#ELDERLY

Elderly_cohort <- filter(problemområde4, pt_age_yrs <120, pt_age_yrs >65)

library(table1)

Elderly_cohort$inj_dominant<-factor(Elderly_cohort$inj_dominant, levels=c(1,2),
       labels=c("Blunt", "Penetrating"))

                label(Elderly_cohort$NISS)              <- "New Injury Severity Score"
                label(Elderly_cohort$pre_sbp_value)    <- "Pre Hospital Systolic BP"
                label(Elderly_cohort$ed_sbp_value)     <- "Emergency Department Systolic BP"
                label(Elderly_cohort$pt_age_yrs)        <- "Age"

                units(Elderly_cohort$pre_sbp_value)  <- "mmHg"
                units(Elderly_cohort$ed_sbp_value)   <- "mmHg"
                units(Elderly_cohort$pt_age_yrs)    <-"Years"

                table1(~ pt_age_yrs + NISS + pre_sbp_value + ed_sbp_value, data=Elderly_cohort, overall="Elderly")
                   
#PENETRATING
                
    Penetrating_1 <-filter(problemområde5, AISCode_01 <600000 & AISCode_01 >300000 & AIS_sev01>2 & AIS_sev01<7)
    Penetrating_2 <-filter(problemområde5, AISCode_02 <600000 & AISCode_02 >300000 & AIS_sev02>2 & AIS_sev02<7)
    Penetrating_3 <-filter(problemområde5, AISCode_03 <600000 & AISCode_03 >300000 & AIS_sev03>2 & AIS_sev03<7)
    Penetrating_4 <-filter(problemområde5, AISCode_04 <600000 & AISCode_04 >300000 & AIS_sev04>2 & AIS_sev04<7)
    Penetrating_5 <-filter(problemområde5, AISCode_05 <600000 & AISCode_05 >300000 & AIS_sev05>2 & AIS_sev05<7)
    Penetrating_6 <-filter(problemområde5, AISCode_06 <600000 & AISCode_06 >300000 & AIS_sev06>2 & AIS_sev06<7)
    Penetrating_7 <-filter(problemområde5, AISCode_07 <600000 & AISCode_07 >300000 & AIS_sev07>2 & AIS_sev07<7)
    Penetrating_8 <-filter(problemområde5, AISCode_08 <600000 & AISCode_08 >300000 & AIS_sev08>2 & AIS_sev08<7)
    Penetrating_9 <-filter(problemområde5, AISCode_09 <600000 & AISCode_09 >300000 & AIS_sev09>2 & AIS_sev09<7)
    Penetrating_10 <-filter(problemområde5, AISCode_10 <600000 & AISCode_10 >300000 & AIS_sev10>2 & AIS_sev10<7)
    Penetrating_11 <-filter(problemområde5, AISCode_11 <600000 & AISCode_11 >300000 & AIS_sev11>2 & AIS_sev11<7)
    Penetrating_12 <-filter(problemområde5, AISCode_12 <600000 & AISCode_12 >300000 & AIS_sev12>2 & AIS_sev01<7)
    Penetrating_12 <-filter(problemområde5, AISCode_12 <600000 & AISCode_12 >300000 & AIS_sev12>2 & AIS_sev12<7)
    Penetrating_13 <-filter(problemområde5, AISCode_13 <600000 & AISCode_13 >300000 & AIS_sev13>2 & AIS_sev13<7)
    Penetrating_14 <-filter(problemområde5, AISCode_14 <600000 & AISCode_14 >300000 & AIS_sev14>2 & AIS_sev14<7)
    Penetrating_15 <-filter(problemområde5, AISCode_15 <600000 & AISCode_15 >300000 & AIS_sev15>2 & AIS_sev15<7)
    Penetrating_16 <-filter(problemområde5, AISCode_16 <600000 & AISCode_16 >300000 & AIS_sev16>2 & AIS_sev16<7)
    Penetrating_17 <-filter(problemområde5, AISCode_17 <600000 & AISCode_17 >300000 & AIS_sev17>2 & AIS_sev17<7)
    Penetrating_18 <-filter(problemområde5, AISCode_18 <600000 & AISCode_18 >300000 & AIS_sev18>2 & AIS_sev18<7)
    Penetrating_19 <-filter(problemområde5, AISCode_19 <600000 & AISCode_19 >300000 & AIS_sev19>2 & AIS_sev19<7)
    Penetrating_20 <-filter(problemområde5, AISCode_20 <600000 & AISCode_20 >300000 & AIS_sev20>2 & AIS_sev20<7)
    Penetrating_21 <-filter(problemområde5, AISCode_21 <600000 & AISCode_21 >300000 & AIS_sev21>2 & AIS_sev21<7)
    Penetrating_22 <-filter(problemområde5, AISCode_22 <600000 & AISCode_22 >300000 & AIS_sev22>2 & AIS_sev22<7)
    Penetrating_23 <-filter(problemområde5, AISCode_23 <600000 & AISCode_23 >300000 & AIS_sev23>2 & AIS_sev23<7)
    Penetrating_24 <-filter(problemområde5, AISCode_24 <600000 & AISCode_24 >300000 & AIS_sev24>2 & AIS_sev24<7)
    Penetrating_25 <-filter(problemområde5, AISCode_25 <600000 & AISCode_25 >300000 & AIS_sev25>2 & AIS_sev25<7)
    Penetrating_26 <-filter(problemområde5, AISCode_26 <600000 & AISCode_26 >300000 & AIS_sev26>2 & AIS_sev26<7)
    Penetrating_27 <-filter(problemområde5, AISCode_27 <600000 & AISCode_27 >300000 & AIS_sev27>2 & AIS_sev27<7)
    Penetrating_28 <-filter(problemområde5, AISCode_28 <600000 & AISCode_28 >300000 & AIS_sev28>2 & AIS_sev28<7)
    Penetrating_29 <-filter(problemområde5, AISCode_29 <600000 & AISCode_29 >300000 & AIS_sev29>2 & AIS_sev29<7)
    Penetrating_30 <-filter(problemområde5, AISCode_30 <600000 & AISCode_30 >300000 & AIS_sev30>2 & AIS_sev30<7)
    Penetrating_31 <-filter(problemområde5, AISCode_31 <600000 & AISCode_31 >300000 & AIS_sev31>2 & AIS_sev31<7)
    Penetrating_32 <-filter(problemområde5, AISCode_32 <600000 & AISCode_32 >300000 & AIS_sev32>2 & AIS_sev32<7)
    Penetrating_33 <-filter(problemområde5, AISCode_33 <600000 & AISCode_33 >300000 & AIS_sev33>2 & AIS_sev33<7)
    Penetrating_34 <-filter(problemområde5, AISCode_34 <600000 & AISCode_34 >300000 & AIS_sev34>2 & AIS_sev34<7)
    Penetrating_35 <-filter(problemområde5, AISCode_35 <600000 & AISCode_35 >300000 & AIS_sev35>2 & AIS_sev35<7)
    Penetrating_36 <-filter(problemområde5, AISCode_36 <600000 & AISCode_36 >300000 & AIS_sev36>2 & AIS_sev36<7)
    Penetrating_37 <-filter(problemområde5, AISCode_37 <600000 & AISCode_37 >300000 & AIS_sev37>2 & AIS_sev37<7)
    Penetrating_38 <-filter(problemområde5, AISCode_38 <600000 & AISCode_38 >300000 & AIS_sev38>2 & AIS_sev38<7)
    Penetrating_39 <-filter(problemområde5, AISCode_39 <600000 & AISCode_39 >300000 & AIS_sev39>2 & AIS_sev39<7)
    Penetrating_40 <-filter(problemområde5, AISCode_40 <600000 & AISCode_40 >300000 & AIS_sev40>2 & AIS_sev40<7)
    Penetrating_41 <-filter(problemområde5, AISCode_41 <600000 & AISCode_41 >300000 & AIS_sev41>2 & AIS_sev41<7)
    Penetrating_42 <-filter(problemområde5, AISCode_42 <600000 & AISCode_42 >300000 & AIS_sev42>2 & AIS_sev42<7)
    Penetrating_43 <-filter(problemområde5, AISCode_43 <600000 & AISCode_43 >300000 & AIS_sev43>2 & AIS_sev43<7)
    Penetrating_44 <-filter(problemområde5, AISCode_44 <600000 & AISCode_44 >300000 & AIS_sev44>2 & AIS_sev44<7)
    Penetrating_45 <-filter(problemområde5, AISCode_45 <600000 & AISCode_45 >300000 & AIS_sev45>2 & AIS_sev45<7)
    Penetrating_46 <-filter(problemområde5, AISCode_46 <600000 & AISCode_46 >300000 & AIS_sev46>2 & AIS_sev46<7)
    Penetrating_47 <-filter(problemområde5, AISCode_47 <600000 & AISCode_47 >300000 & AIS_sev47>2 & AIS_sev47<7)
    Penetrating_48 <-filter(problemområde5, AISCode_48 <600000 & AISCode_48 >300000 & AIS_sev48>2 & AIS_sev48<7)
    Penetrating_49 <-filter(problemområde5, AISCode_49 <600000 & AISCode_49 >300000 & AIS_sev49>2 & AIS_sev49<7)
    Penetrating_50 <-filter(problemområde5, AISCode_50 <600000 & AISCode_50 >300000 & AIS_sev50>2 & AIS_sev50<7)

    Penetrating_cohort <- Reduce(function(x, y) merge(x, y, all=TRUE),list(Penetrating_1, Penetrating_2, Penetrating_3, Penetrating_4, Penetrating_5, Penetrating_6, Penetrating_7, Penetrating_8, Penetrating_9, Penetrating_10,Penetrating_11, Penetrating_12, Penetrating_13, Penetrating_14,Penetrating_15,Penetrating_16, Penetrating_17, Penetrating_18, Penetrating_19, Penetrating_20, Penetrating_21, Penetrating_22, Penetrating_23, Penetrating_24, Penetrating_25, Penetrating_26, Penetrating_27, Penetrating_28, Penetrating_29, Penetrating_30,Penetrating_31, Penetrating_32, Penetrating_33, Penetrating_34, Penetrating_35,Penetrating_36, Penetrating_37, Penetrating_38, Penetrating_39, Penetrating_40,Penetrating_41, Penetrating_42, Penetrating_43, Penetrating_44, Penetrating_45,Penetrating_46, Penetrating_47, Penetrating_48, Penetrating_49, Penetrating_50))

Penetrating_cohort <- filter(Penetrating_cohort, inj_dominant == 2)

# TABLE ONE
  
library(dplyr)
  
  Elderly_cohort$Cohort <- "Geriatric"
  Penetrating_cohort$Cohort <- "Penetrating"
  SevereTBI_cohort1$Cohort <- "Severe TBI"
  Shock_cohort$Cohort <- "Shock"
  
  merged_cohorts <- Reduce(function(x, y) merge(x, y, all=TRUE),
                                     list(SevereTBI_cohort1,Penetrating_cohort, Elderly_cohort, Shock_cohort))

  library(table1)

                  label(merged_cohorts$NISS)              <- "New Injury Severity Score"
                  label(merged_cohorts$pre_sbp_value)    <- "Pre Hospital Systolic BP"
                  label(merged_cohorts$ed_sbp_value)     <- "Emergency Department Systolic BP"
                  label(merged_cohorts$pt_age_yrs)        <- "Age"
                  
                  units(merged_cohorts$pre_sbp_value)  <- "mmHg"
                  units(merged_cohorts$ed_sbp_value)   <- "mmHg"
                  units(merged_cohorts$pt_age_yrs)    <-"Years"

                  table1(~ pt_age_yrs + NISS + pre_sbp_value + ed_sbp_value |Cohort, data=merged_cohorts, overall=)
                  
                  
# FLOWCHART
                  
              
                  library(DiagrammeR)
                  
                  grViz("digraph flowchart {
      node [fontname = Helvetica, shape = rectangle]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
      tab5 [label = '@@5']
      tab6 [label = '@@6']
      tab7 [label = '@@7']
      tab8 [label = '@@8']

      tab1 -> tab2
      tab2 -> tab3 -> tab5
      tab3 -> tab4 
      tab5 -> tab6
      tab5 -> tab7
      tab5 -> tab8
      }

      [1]: 'n=12099'
      [2]: 'n=11522 '
      [3]: 'n=8226'
      [4]: 'n=3296'
      [5]: 'n=2053'
      [6]: 'n=2024'
      [7]: 'n=2417'
      [8]: 'n=1656'
      ")
                  
   # Måste fixas så att den refererar till dataframes               
                  
  # INCIDENCE
                               
    install.packages("incidence")
    library(incidence)
    
    Incidence_test <- problemområde$Problemomrade_.FMP$Ankomst_te
    
                
    
```

                  
