---
title: "Incidence of Opportunities for Improvement - Study Plan"
output: pdf_document
bibliography: citations.bib
link-citations: yes
csl: bmcemerg.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Introduction
### Background

Defined as physical injury and the body’s associated response [@Gerdin2015], trauma is one of the primary causes for mortality and morbidity throughout the world. [@GlobalStats] It is a disease estimated to claim several million lives each year and constitutes a massive burden on the global economy. [@GlobalStats] For every death by trauma, three patients are rendered permanently disabled [@Trauma], which significantly amplifies the social and economic impacts of the disease as well as the importance of quality trauma care.

Approximately half of all deaths attributable to trauma occur within minutes of the initial injury [@Trauma], making primary prevention the most effective way to significantly address mortality and morbidity. The second half however, often as a result of neurological dysfunction, sepsis or multisystem organ failure, occurs later and can to a point, be prevented [@Trauma]. Evidence of this is seen in several hospitals, when comparing mortality rates prior to and after  introduction of the Advanced Trauma Life Support (ATLS) method, a systematized approach to initial rapid trauma evaluation [@ATLS2][@ATLSItaly][@ATLS3].

In 2008, the American College of Surgeons initiated an effort to improve and systematize trauma care across the continent through their Trauma Quality Improvement Program (TQIP) [@TQIP]. Inherent to the program, is a grouping of trauma patients into cohorts, using the Abbreviated Injury Scale (AIS) grading system, which forms a number of seven digits indicating (i) region of injury, (ii) type of anatomical structure, (iii) specific anatomical structure, (iv) level of injury and (v) severity of injury [@TQIP][@AIS]. In our study, we have chosen to specifically include five cohorts, defined as follows: 


1. Blunt multisystem injury with an AIS severity score of > 3 in a least two regions of the body
2. Penetrating truncal injury with an AIS severity score of > 3 in the regions of the neck, chest, or abdomen
3. Shock patients with a systolic blood pressure < 90 mmHg
4. Patients with isolated traumatic brain injury (TBI)
5. Elderly patients (over 65 years of age) without isolated hip fractures [@TQIP]

(ACS, TQIP benchmark report 2013, 2015, 2017) (Quality Benchmarking in Trauma: from the NTDB to TQIP - 2018)(The Trauma Quality Improvement Program of the American College of Surgeons Committee on Trauma - J Am Surg)

*Leta vidare efter definitionen på kohorterna du letar efter. Notera att Am Co Su har gjort guidelines med tre, fem och tio kohorter. Det finns mest info om den med 10st och den verkar även vara mest aktuell i dagsläget.*

Two pillars of trauma quality improvement are benchmarking of outcomes and multidisciplinary mortality and morbidity reviews. Benchmarking of outcomes is often done by comparing outcomes between or within centers across two or more of the TQIP cohorts. The multidisciplinary mortality and morbidity review boards, aims to identify possibilities for improvement and implement corrective initiatives. (Citation needed)

While much is known about mortality outcomes between the trauma cohorts, little research has been conducted on how the incidence of opportunities for improvement varies across these cohorts. As we strive to improve the quality of our trauma care, this an important gap in knowledge that needs to be addressed. We will argue that it is plausible to assume that the number of opportunities for improvements may vary between cohorts and that the result could give us a hint on where to focus our limited resources.

### Aims

The overarching aim of this study is to further investigate the quality of early trauma care at Karolinska University Hospital trauma center in Stockholm, Sweden. 

**Specific aims:**


* To estimate the incidence of opportunities for improvement in each of the TQIP trauma patient cohorts in the Karolinska trauma and trauma care quality registries.
* To compare incidence of opportunities for improvement between cohorts and plot them as a function over time.

## Methods
### Study design 

An single blinded institutional retrospective cohort study will be conducted, using data from two entities: the Karolinska University Hospital trauma and trauma care quality registries. The registries will be linked and the patients either divided between the TQIP cohorts or excluded determined by their adherence, or lack thereof, to the AIS eligibility criteria. Thereafter the incidence of ‘opportunities for improvement’, a dichotomous proxy measure for sub optimal care, will be estimated, compared between cohorts and plotted as a function over time. 

All of this, the extraction of data, the linking of data sets, the division of patients into cohorts, the exclusion of patients and the subsequent analyses, will first be applied to a simulated set of data. This will generate an algorithm, which after rigorous examination can be applied to the real data set, thus blinding the developer from the results.

### Setting 

Karolinska University Hospital is the leading trauma care center in Stockholm, Sweden and where the majority of the severe trauma cases are processed. There are a number of smaller  trauma hospitals in the Stockholm area, but Karolinska University Hospital is the only one which could be compared to a level one trauma facility, though it lacks formal verification by the American College of Surgeons as of yet. [@Granstrom] In Stockholm, trauma patients are tagged by paramedics in a pre-hospital setting as a priority one or two, by assessing vital physiological parameters and anatomical criteria. The physiological parameters to being tagged as a level one priority are systolic BP (<90 mmHg), respiratory rate (<10 or >29) and Glasgow Coma Scale (GCS) grading for impaired consciousness (<14). An anatomical criterion could be an unstable or deformed chest. [@Traumateam]

Once tagged as a priority one trauma, the injuries are considered directly life threatening, the patient in need of a full trauma team, and a transport by ambulance or helicopter to the Karolinska University Hospital trauma center is subsequently undertaken. At arrival, they are taken to the trauma room where they are met by a surgeon who assumes the role as trauma leader, an anesthesiologist, an orthopedic surgeon, a radiologist, a surgical nurse, an assistant surgical nurse, a nurse anesthetist, an emergency medicine nurse, an emergency medicine assistant nurse and a radiology nurse. A primary survey is then conducted following the ATLS method for initial rapid trauma evaluation and the next course of action is decided upon. [@Traumateam] [@Granstrom]

Patients treated at Karolinska University Hospital, who required trauma team activation or retrospectively were found to have injuries corresponding to a New Injury Severity Score (NISS, a validated model for grading of trauma injury severity) [@NISS] grading of 15 or greater, since 2012 are included in the hospitals trauma registry. This includes patients transferred to the hospital within 7 days of an injury corresponding to a NISS grading of >15. (Manual SweTrau) Excluded are patient who triggers trauma team activation despite not having suffered a traumatic injury and patients whose solitary injury is chronic subdural hematoma. The registry is a part of Sweden's larger  national trauma registry, SweTrau, and contains information about prehospital type of transport, prehospital vital physiological parameters, type of injury, vital physiological parameters at arrival, intention of injury, important laboratory parameters and several other data points pertaining to the same category. (Manual SweTrau)

Follow up is conducted after 30 days and registers survival, days in ventilator, GCS at discharge, highest level of care received, location of discharge, if there were a transfer to another unit of care and if there was an autopsy performed as well as 15 hospital specific variables. *vet inte vilka dessa är i fallet av Karolinskas traumaregister, får kompletteras efter att ha fått register* The Karolinska care quality registry contains a subset of those patient cases, selected for multidisciplinary mortality and morbidity review, since 2014. In each of the patient cases selected for review, one question is posed and subsequently answered, namely: was there an opportunity for improvement in the care of this patient?
(ACS,TQIP benchmark report 2015)

### Participants 

Eligible for inclusion are all patients in the Karolinska trauma and trauma care quality registries, who suffered blunt or penetrating trauma and whose injuries had an AIS grading corresponding to that of one of the five TQIP cohorts. In addition, the patient case must have been selected for a multidisciplinary mortality and morbidity review board meeting in order to qualify. The trauma room discharge disposition and the hospital discharge disposition, cannot both be unknown.

Excluded are all patients aged 15 or below, since pediatric physiology, panorama of injuries and method of treatment, differ vastly from those of the adult. The choice of age 15 as a cutoff point stems from the American College of Surgeons' TQIP study directives. Moreover, excluded are patients who were pronounced dead on arrival, patients who suffered from an isolated gunshot wound to the brain, patients with severe burns and patients with pre-existing advanced directives to withhold life sustaining interventions. *Finner ingen data om tidigare behandlingsbegränsningar i SweTrau-manualen, avvaktar med att ta bort meningen tills dess att jag fått kommentarer. Något liknande kanske kan formuleras med hjälp av variabeln "ASA-klassifikation innan trauma".* Lastly, all patient with insufficient data, as to render any attempt of categorization into the TQIP cohorts impossible, are excluded.
(ACS,TQIP benchmark report 2015)

### Variables 

As the primary outcome measure, the dichotomous variable ‘opportunity for improvement’ (yes/no), as defined in the trauma care quality registry, is used. An opportunity for improvement is considered to apply if the multidisciplinary review board have deemed it so. The primary exposure of interest was having suffered severe blunt or penetrating  traumatic injuries, corresponding to a NISS grading of>15, triggering trauma team activation and ensuing care at Karolinska University Hospital. 

##### Potential effect modifiers

There is a possibility that patients who would otherwise be characterized as trauma patients retrospectively, namely those who did not initiate trauma team activation, but satisfied the NISS scoring criteria, were subject to systematic mis- or underdiagnosis and not included in the registries as a result. As such, they may have been undertreated and may, as a group, have a lower true incidence of opportunities for improvement, then the reported one. There is also a possibility that the patients excluded as a result of having insufficient data, were systematically better or worse of than the patients with complete data.

*mycket osäker på allt detta, tänk vidare imorgon*

### Measurement 

The answer ‘yes’ or ‘no’ to the dichotomous variable ‘opportunities for improvement’ found in the Karolinska trauma care quality registry, was contingent on the consensus of the discussion in the multidisciplinary review board meeting. For each case, the attending physicians and nurse made a decision based on certain guiding questions, e.g.: “Were the material resources available appropriate for the type and severity of the injuries?” or “Were there enough physicians, nurses, assistant nurses...” and so on. 

*Jag har haft svårt att hitta den exakta mallen som används för att vägleda dessa beslut. Tar gärna emot tips om hur jag hittar den.*

### Bias

The method and algorithm for data analysis will be developed on a step-by-step basis using simulated data. It will be rigorously tested throughout its development process, until the results using the simulated data set is deemed satisfactory. When that is the case, the algorithm will be reviewed by a trained programmer and statistician. After approval by the programmer and statistician, the algorithm will not be changed, and the data, as a result, will not be skewed by the bias of the developer.

### Study size 

The collections of data most applicable to our study question are the Karolinska trauma and trauma care quality registries, which is why they were chosen as our primary source of data. The Karolinska trauma registry contains information about roughly 21,000 patients, 2,200 of whom are also included in the Karolinska trauma care quality registry. The data point 'opportunity for improvement' is solely available in the trauma care quality registry, and as a result, our study population can never be larger than its total number of patients, though it will most likely be significantly reduced after exclusion.

*något resonemang om studiestorlek och statistical power*

### Quantitative variables

The majority of the variables dealt with in order to categorize patients into the TQIP cohorts are qualitative in nature. The outcome measure is also a qualitative variable. However, age, systolic BP and AIS severity score are quantitative variables used in order to group the patients. Age will be used in two ways, firstly to exclude all patients below the age of 15 from the data set, and secondly in order to group the patients above the age of 65 into their specific cohort. Systolic BP is used to determine whether or not a patient could be grouped into the 'shock' cohort. AIS severity score was used to determine eligibility to the study as a whole.
*Säkerställ att du skriver om rätt sak*

### Statistical methods 

The statistical programming language R will be used in order to merge the extracted data sets from the registries. All non-essential columns of variables will be removed and the data will be cleaned. Inputs like "999" will be systematically changed to an informational value or removed as per instruction in the SweTrau Manual. Thereafter patients will be grouped and excluded according to the cohort definitions, inclusion criteria and exclusion criteria listed above. All patients who lacks necessary data for categorization into cohorts will be removed. Once grouping and exclusion have been successfully accomplished, the incidence of 'opportunities for improvements' will be calculated in each cohort. A linear regression model will then be applied to the data in order to estimate the trends of these incidences over time. All excluded patients, as well as their reason for exclusion, will be noted.

*Kika mer på detta/utvidga*


